export const getAllProducts = () => {
  return [
    {
      id: 'SHHN-001',
      slug: 'sherlock-holmes-a-study-in-scarlet-(1887)',
      name: "Sherlock Holmes - A Study In Scarlet (1887)",
      category: 'Best Seller',
      price: 150_000,
      stock: 0,
      imageUrl: '/assets/images/Sherlock-Holmes-A-Study-In-Scarlet-(1887).svg',
      description: `A Study in Scarlet is an 1887 detective novel by British writer Arthur Conan Doyle. The story marks the first appearance of Sherlock Holmes and Dr. Watson, who would become the most famous detective duo in English literature.`,
      genre: "Mistery",
      novelist: "Sir Arthur Conan Doyle",
      pages: '270 Pages',
      language: "Indonesia & English",
      weight: '0.400 Kg'
    },
    {
      id: 'SHHN-002',
      slug: 'sherlock-holmes-the-sign-of-the-four-(1890)',
      name: "Sherlock Holmes - The Sign of The Four (1890)",
      category: 'Best Seller',
      price: 150_000,
      stock: 15,
      imageUrl: '/assets/images/Sherlock-Holmes-The-Sign-of-The-Four-(1890).svg',
      description: `The Sign of the Four, also called The Sign of Four, is an 1890 detective novel, and it is the second novel featuring Sherlock Holmes by British writer Sir Arthur Conan Doyle. Doyle wrote four novels and 56 short stories featuring the fictional detective.`,
      genre: "Mistery",
      novelist: "Sir Arthur Conan Doyle",
      pages: '196 Pages',
      language: "Indonesia & English",
      weight: '0.155 Kg'
    },
    {
      id: 'SHHN-003',
      slug: 'the-adventures-of-sherlock-holmes-(1892)',
      name: "The Adventures of Sherlock Holmes (1892)",
      category: 'Popular',
      price: 120_000,
      stock: 50,
      imageUrl: '/assets/images/The-Adventures-of-Sherlock-Holmes-(1892).svg',
      description: `The Adventures of Sherlock Holmes is a collection of short stories by British writer Arthur Conan Doyle, first published on 14 October 1892. It contains the earliest short stories featuring the consulting detective Sherlock Holmes, which had been published in twelve monthly issues of The Strand Magazine from July 1891 to June 1892. The stories are collected in the same sequence, which is not supported by any fictional chronology. The only characters common to all twelve are Holmes and Dr. Watson, and all are related in first-person narrative from Watson's point of view.`,
      genre: "Mistery",
      novelist: "Sir Arthur Conan Doyle",
      pages: '369 Pages',
      language: "Indonesia & English",
      weight: '0.215 Kg'
    },
    {
      id: 'SHHN-004',
      slug: 'the-memoirs-of-sherlock-holmes-(1894)',
      name: "The Memoirs of Sherlock Holmes (1894)",
      category: 'Popular',
      price: 150_000,
      stock: 45,
      imageUrl: '/assets/images/The-Memoirs-of-Sherlock-Holmes-(1894).svg',
      description: `The Memoirs of Sherlock Holmes is a collection of short stories by British writer Arthur Conan Doyle, first published late in 1893 with 1894 date. It was first published in the UK by G. Newnes Ltd., and was published in the US by Harper & Brothers in February 1894. It was the second collection featuring the consulting detective Sherlock Holmes, following The Adventures of Sherlock Holmes. Like the first it was illustrated by Sidney Paget.`,
      genre: "Mistery",
      novelist: "Sir Arthur Conan Doyle",
      pages: '308 Pages',
      language: "Indonesia & English",
      weight: '0.200 Kg'
    },
    {
      id: 'SHHN-005',
      slug: 'sherlock-holmes-the-hound-of-the-baskervilles-(1901-1902)',
      name: "Sherlock Holmes - The Hound of The Baskervilles (1901-1902)",
      category: 'Best Seller',
      price: 100_000,
      stock: 10,
      imageUrl: '/assets/images/Sherlock-Holmes-The-Hound-of-The-Baskervilles-(1901-1902).svg',
      description: `The Hound of the Baskervilles is the third of the four crime novels by British writer Arthur Conan Doyle featuring the detective Sherlock Holmes. Originally serialised in The Strand Magazine from August 1901 to April 1902, it is set largely in Dartmoor, Devon, in England's West Country and follows Holmes and Watson investigating the legend of a fearsome, diabolical hound of supernatural origin. This was the first appearance of Holmes since his apparent death in "The Final Problem", and the success of The Hound of the Baskervilles led to the character's eventual revival.`,
      genre: "Mistery",
      novelist: "Sir Arthur Conan Doyle",
      pages: '208 Pages',
      language: "Indonesia & English",
      weight: '0.15 Kg'
    },
    {
      id: 'SHHN-006',
      slug: 'the-return-of-sherlock-holmes-(1905)',
      name: "The Return of Sherlock Holmes (1905)",
      category: 'Popular',
      price: 108_000,
      stock: 35,
      imageUrl: '/assets/images/The-Return-of-Sherlock-Holmes-(1905).svg',
      description: `The Return of Sherlock Holmes is a 1905 collection of 13 Sherlock Holmes stories, originally published in 1903-1904, by British writer Arthur Conan Doyle. The stories were published in the Strand Magazine in Britain and Collier's in the United States.`,
      genre: "Mistery",
      novelist: "Sir Arthur Conan Doyle",
      pages: '374 Pages',
      language: "Indonesia & English",
      weight: '0.25 Kg'
    },
    {
      id: 'SHHN-007',
      slug: 'sherlock-holmes-the-valley-of-fear-(1914-1915)',
      name: "Sherlock Holmes - The Valley of Fear (1914-1915)",
      category: 'Best Seller',
      price: 80_000,
      stock: 20,
      imageUrl: '/assets/images/Sherlock-Holmes-The-Valley-of-Fear-(1914-1915).svg',
      description: `The Valley of Fear is the fourth and final Sherlock Holmes novel by British writer Arthur Conan Doyle. It is loosely based on the Molly Maguires and Pinkerton agent James McParland. The story was first published in the Strand Magazine between September 1914 and May 1915. The first book edition was copyrighted in 1914, and it was first published by George H. Doran Company in New York on 27 February 1915, and illustrated by Arthur I. Keller.`,
      genre: "Mistery",
      novelist: "Sir Arthur Conan Doyle",
      pages: '208 Pages',
      language: "Indonesia & English",
      weight: '0.15 Kg'
    },
    {
      id: 'SHHN-008',
      slug: 'sherlock-holmes-his-last-bow-(1917)',
      name: "Sherlock Holmes - His Last Bow (1917)",
      category: 'Popular',
      price: 150_000,
      stock: 0,
      imageUrl: '/assets/images/Sherlock-Holmes-His-Last-Bow-(1917).svg',
      description: `His Last Bow: Some Reminiscences of Sherlock Holmes is a 1917 collection of previously published Sherlock Holmes stories by British writer Arthur Conan Doyle, including the titular short story, "His Last Bow. The War Service of Sherlock Holmes" (1917). The collection's first US edition adjusts the anthology's subtitle to Some Later Reminiscences of Sherlock Holmes.`,
      genre: "Mistery",
      novelist: "Sir Arthur Conan Doyle",
      pages: '300 Pages',
      language: "Indonesia & English",
      weight: '0.4 Kg'
    },

  ]
}